const translationVi = {
  checkIn: 'Chấm công',
  contact: 'Liên hệ',
  home: 'Trang chủ',
  profile: 'Hồ sơ',
  notification: 'Thông báo',
  settings: 'Cài đặt',
  logout: 'Đăng xuất',
  login: 'Đăng nhập',
  register: 'Đăng ký',
  forgotPassword: 'Quên mật khẩu',
  resetPassword: 'Đặt lại mật khẩu',
  verifyEmail: 'Xác thực email',
  verifyPhone: 'Xác thực số điện thoại',
  homeScreenMessage: 'Trang chủ',
  contactScreenMessage: 'Liên hệ',
  checkInScreenMessage: 'Chấm công',
  notificationScreenMessage: 'Thông báo',
  profileScreenMessage: 'Hồ sơ',
  loginScreenMessage: 'Đăng nhập',
  inputCompanyCode: 'Vui lòng mã công ty để tiếp tục ',
  companyCode: 'Mã công ty',
  inputCompanyCodePlaceholder: 'Vui lòng nhập mã công ty',
  inputAccount: 'Tài khoản',
  inputAccountPlaceholder: 'Vui lòng nhập tài khoản',
  inputPassword: 'Mật khẩu',
  inputPasswordPlaceholder: 'Vui lòng nhập mật khẩu',
  loginWithOtherAccount: 'Đăng nhập bằng tài khoản khác',
  cancel: 'Hủy',
  select: 'Chọn',
  approve: 'Phê duyệt',
  approveLeave: 'Phê duyệt nghỉ',
  approveOvertime: 'Phê duyệt làm thêm',
  approveExplanation: 'Phê duyệt giải trình công',
  approveHistory: 'Lịch sử phê duyệt',
  leave: 'Nghỉ',
  overtime: 'Làm thêm',
  explanation: 'Giải trình công',
  history: 'Lịch sử phê duyệt',
  registerLeave: 'Đăng ký nghỉ',
  registerOvertime: 'Đăng ký làm thêm',
  registerExplanation: 'Đăng ký giải trình công',
  registerHistory: 'Lịch sử đăng ký',
  loginError: 'Đăng nhập thất bại',

  ok: 'OK',
  hello: 'Xin chào',
  fromDate: 'Từ ngày',
  toDate: 'Đến ngày',
  reason: 'Lý do',
  applySameType: 'Áp dụng cùng loại công',
  declareByDay: 'Khai báo theo ngày',
  declareByHour: 'Vắng mặt việc riêng theo giờ',
  sendApprove: 'Gửi duyệt',
  availableLeave: 'Ngày phép khả dụng',
  usedLeave: 'Ngày phép đã nghỉ',
  remainingLeave: 'Ngày phép còn lại',
  selectDate: 'Chọn ngày',
  reasonPlaceholder: 'Vui lòng nhập lý do',
} as const;

const translationEn = {
  checkIn: 'Check In',
  contact: 'Contact',
  home: 'Home',
  profile: 'Profile',
  notification: 'Notification',
  settings: 'Settings',
  logout: 'Logout',
  login: 'Login',
  register: 'Register',
  forgotPassword: 'Forgot password',
  resetPassword: 'Reset password',
  verifyEmail: 'Verify email',
  verifyPhone: 'Verify phone number',
  homeScreenMessage: 'Home Screen',
  contactScreenMessage: 'Contact Screen',
  checkInScreenMessage: 'Check In Screen',
  notificationScreenMessage: 'Notification Screen',
  profileScreenMessage: 'Profile Screen',
  loginScreenMessage: 'Login Screen',
  inputCompanyCode: 'Please enter company code to continue',
  companyCode: 'Company code',
  inputCompanyCodePlaceholder: 'Please enter company code',
  inputAccount: 'Account',
  inputAccountPlaceholder: 'Please enter account',
  inputPassword: 'Password',
  inputPasswordPlaceholder: 'Please enter password',
  loginWithOtherAccount: 'Login with other account',
  cancel: 'Cancel',
  select: 'Select',
  approve: 'Approve',
  approveLeave: 'Approve leave',
  approveOvertime: 'Approve overtime',
  approveExplanation: 'Approve explanation',
  approveHistory: 'Approve history',
  leave: 'Leave',
  overtime: 'Overtime',
  explanation: 'Explanation',
  history: 'History',
  registerLeave: 'Register leave',
  registerOvertime: 'Register overtime',
  registerExplanation: 'Register explanation',
  registerHistory: 'Register history',
  loginError: 'Login error',
  ok: 'OK',
  hello: 'Hello',
  fromDate: 'From date',
  toDate: 'To date',
  reason: 'Reason',
  applySameType: 'Apply same type',
  declareByDay: 'Declare by day',
  declareByHour: 'Declare by hour',
  sendApprove: 'Send approve',
  availableLeave: 'Available leave',
  usedLeave: 'Used leave',
  selectDate: 'Select date',
  reasonPlaceholder: 'Please enter reason',
  remainingLeave: 'Remaining leave',
} as const;

export const translations = {
  vi: translationVi,
  en: translationEn,
} as const;

export type LanguageCode = keyof typeof translations;
export type TranslationKey = keyof (typeof translationVi);

export const languageDisplayNames: Record<LanguageCode, string> = {
  vi: 'Tiếng Việt',
  en: 'English',
};

export const defaultLanguage: LanguageCode = 'vi';

export const getTexts = (language: LanguageCode) =>
  translations[language] ?? translations[defaultLanguage];

export const Texts = translations[defaultLanguage];