const ROUTERS = {
  Login: 'Login',
  Register: 'Register',
  CompanyCode: 'CompanyCode',
  Auth: 'Auth',
  Main: 'Main',
  Home: 'Home',
  Profile: 'Profile',
  Setting: 'Setting',
  Notification: 'Notification',
  CheckIn: 'CheckIn',
  Contact: 'Contact',
  MainTabs: 'MainTabs',
  Approve: 'Approve',
  RegisterLeave: 'RegisterLeave',
  RegisterOvertime: 'RegisterOvertime',
  RegisterExplanation: 'RegisterExplanation',
  RegisterHistory: 'RegisterHistory',
  ApproveLeave: 'ApproveLeave',
  ApproveOverTime: 'ApproveOverTime',
  ApproveExplain: 'ApproveExplain',
  ApproveHistory: 'ApproveHistory',
  RegisterHistoryDetail: 'RegisterHistoryDetail',
  ApproveHistoryDetail: 'ApproveHistoryDetail',
} as const;
export default ROUTERS;
